export const data = [
	{
		id: 1,
		type: 'blue',
		path: 'https://iili.io/ilj9IV.jpg',
		name: 'Anakin',
	},
	{
		id: 2,
		type: 'red',
		path: 'https://iili.io/iljHhB.jpg',
		name: 'Darth Vader',
	},
	{
		id: 3,
		type: 'red',
		path: 'https://iili.io/ilhpmQ.jpg',
		name: 'Darth Maul',
	},
	{
		id: 4,
		type: 'blue',
		path: 'https://iili.io/ilhmkx.jpg',
		name: 'Obi-Wan',
	},
	{
		id: 5,
		type: 'blue',
		path: 'https://iili.io/iM00fn.jpg',
		name: 'Amidala',
	},
	{
		id: 6,
		type: 'darkorange',
		path: 'https://iili.io/iMMU41.jpg',
		name: 'Boba Fett',
	},
	{
		id: 7,
		type: 'blue',
		path: 'https://iili.io/iMWBxR.jpg',
		name: 'Chewbacca',
	},
	{
		id: 8,
		type: 'blue',
		path: 'https://iili.io/iMXlTJ.jpg',
		name: 'Grogu',
	},
	{
		id: 9,
		type: 'blue',
		path: 'https://iili.io/iMhEAu.jpg',
		name: 'Han Solo',
	},
	{
		id: 10,
		type: 'darkorange',
		path: 'https://iili.io/iMjmkF.jpg',
		name: 'Jar Jar Binks',
	},
	{
		id: 11,
		type: 'blue',
		path: 'https://iili.io/iMNTwg.jpg',
		name: 'Leia',
	},
	{
		id: 12,
		type: 'red',
		path: 'https://iili.io/iMO6In.jpg',
		name: 'Palpatine',
	},
	{
		id: 13,
		type: 'blue',
		path: 'https://iili.io/iMv11f.jpg',
		name: 'Qui Gon Jinn',
	},
	{
		id: 14,
		type: 'blue',
		path: 'https://iili.io/iMU5mB.jpg',
		name: 'Yoda',
	},
	{
		id: 15,
		type: 'red',
		path: 'https://iili.io/iWVbV4.jpg',
		name: 'Dark Trooper',
	},
	{
		id: 16,
		type: 'red',
		path: 'https://iili.io/iWVyf2.jpg',
		name: 'Moff Gideon',
	},
	{
		id: 17,
		type: 'red',
		path: 'https://iili.io/iWWfxj.jpg',
		name: 'Commando',
	},
	{
		id: 18,
		type: 'red',
		path: 'https://iili.io/iWWnfV.jpg',
		name: 'Storm Trooper',
	},
	{
		id: 19,
		type: 'blue',
		path: 'https://iili.io/iWhqFV.jpg',
		name: 'C3PO',
	},
	{
		id: 20,
		type: 'darkorange',
		path: 'https://iili.io/iWhBcB.jpg',
		name: 'Ewok',
	},
	{
		id: 21,
		type: 'blue',
		path: 'https://iili.io/iWho91.jpg',
		name: 'Finn',
	},
	{
		id: 22,
		type: 'red',
		path: 'https://iili.io/iWhIta.jpg',
		name: 'Kylo Ren',
	},
	{
		id: 23,
		type: 'darkorange',
		path: 'https://iili.io/iWhAMv.jpg',
		name: 'Mando',
	},
	{
		id: 24,
		type: 'blue',
		path: 'https://iili.io/iWhYcN.jpg',
		name: 'R2-D2',
	},
	{
		id: 25,
		type: 'blue',
		path: 'https://iili.io/iWh0AX.jpg',
		name: 'Rey',
	},
	{
		id: 26,
		type: 'darkorange',
		path: 'https://iili.io/iWhEts.jpg',
		name: 'Sandpeople',
	},
	{
		id: 27,
		type: 'blue',
		path: 'https://iili.io/iWhjl2.jpg',
		name: 'Tobias',
	},
	{
		id: 28,
		type: 'darkorange',
		path: 'https://iili.io/iWwoQa.jpg',
		name: 'Owen',
	},
	{
		id: 29,
		type: 'red',
		path: 'https://iili.io/iWwzCJ.jpg',
		name: 'Dooku',
	},
	{
		id: 30,
		type: 'blue',
		path: 'https://iili.io/iWwT4R.jpg',
		name: 'Ahsoka Tano',
	},
	{
		id: 31,
		type: 'blue',
		path: 'https://iili.io/iWwRYN.jpg',
		name: 'BB-8',
	},
	{
		id: 32,
		type: 'blue',
		path: 'https://iili.io/iWwOZu.jpg',
		name: 'Mas Ameda',
	},
];
